### ISSUE TITLE
How do I enable 'detailed'?

### ISSUE THREAD

**Issue by iagox86** [bnagy/crabstone#8]
Hey, I'm trying to use crabstone for a project, and I'd love to have `detailed` mode enabled. I don't see anything in example/ or test/ that covers details.

I was looking at the source, and it looks like I have to do something special with the first parameter, but I don't understand what I'm looking at.

Any advice? If you give me a simple example, I'm happy to send you a PR with something new for the examples folder.

Thanks!

**Comment by disasmwinnie** [comment]
I needed some hours to find that one too. From the README (capstone and crabstone): 
``Provide details on disassembled instruction (called “decomposer” by others).``
You should have a look at the [source for options](https://github.com/bnagy/crabstone/blob/e3e0a552fcc8d45b7d2e5840456a0d6826271353/lib/crabstone.rb#L467-L471).

To use it, you have to enable the decomposer. Usage example: 

```ruby
require 'crabstone'
include Crabstone

X86_CODE64 = "\x55\x48\x8b\x05\xb8\x13\x00\x00"
cs = Disassembler.new(ARCH_X86, MODE_64)
cs.decomposer = true
cs.disasm(X86_CODE64, 0x1000).each do |ins| 
  puts("#{ins.mnemonic} #{ins.op_str}")
  ins.operands.each do |op|
    puts("\tRegister name: #{cs.reg_name(op[:value][:reg])}") if op.reg?
    if op.mem?
      puts("\tMemory op's displacement: #{op[:value][:mem][:disp]}")
      puts("\tMemory op's base register: #{cs.reg_name(op[:value][:mem][:base])}") if op[:value][:mem][:base] != 0
      puts("\tMemory op's index register: #{cs.reg_name(op[:value][:mem][:index])}") if op[:value][:mem][:index] != 0
      puts("\tMemory op's scale: #{op[:value][:mem][:scale]}")
    end
  end
end
```

**Comment by iagox86** [comment]
Thanks! I tried that out and it looks like it worked!

I tried cs.decomposer, but I don't think I looked deeply enough at the output of disasm().
