### ISSUE TITLE
Push gem to RubyGems.org

### ISSUE THREAD

**Issue by david942j** [bnagy/crabstone#9]
Hello,
I'm one of the developers of [pwntools-ruby](https://github.com/peter50216/pwntools-ruby) and we use crabstone as dependency.
Could you push crabstone to RubyGems.org? Seems all gems on RubyGems.org can only have dependencies that also available on it.

Thanks a lot!

**Comment by david942j** [comment]
Or may I push it to RubyGems.org 😕  ?

**Comment by fallenoak** [comment]
@david942j @bnagy I'd love to see this up on `rubygems.org`, too. I also have a project that makes use of the bindings, and it's a shame I won't be able to just tell users to run `bundle install`.

**Comment by david942j** [comment]
I have pushed the latest version of crabstone to rubygems.org: [link](https://rubygems.org/gems/crabstone) ;)
